export const DRAG = {
	TYPE: 'DRAG_TYPE'
}

export const COLLECTIONS = {
	ADD: 'COLLECTIONS_ADD'
}

export const TASKS = {
	INIT: 'TASKS_INIT',
	UPDATETASKNAME: 'TASKS_UPDATE_TASK_NAME',
	UPDATESTEPNAME: 'TASKS_UPDATE_STEP_NAME'
}
