export const DRAG = {
	TYPE: 'DRAG_TYPE'
}

export const COLLECTIONS = {
	ADD: 'COLLECTIONS_ADD'
}

export const TASKS = {
	INIT: 'TASKS_INIT',
	DISPOSE: 'TASKS_DISPOSE',
	SET_ACTIVE_STEP_ID: 'TASKS_SET_ACTIVE_STEP_ID',
	UPDATE_TASK_NAME: 'TASKS_UPDATE_TASK_NAME',
	UPDATE_STEP_NAME: 'TASKS_UPDATE_STEP_NAME',
	ADD_TASK: 'TASKS_ADD_TASK',
	ADD_STEP: 'TASKS_ADD_STEP',
	SET_PRE_STEP: 'TASKS_SET_PRE_STEP',
	SET_MAIN_STEP: 'TASKS_SET_MAIN_STEP',
}
