<template>
<div class="demo-icon">
	<div><yo-icon name="address-book" /><span>address-book</span></div>
	<div><yo-icon name="address-book-o" /><span>address-book-o</span></div>
	<div><yo-icon name="address-card" /><span>address-card</span></div>
	<div><yo-icon name="address-card-o" /><span>address-card-o</span></div>
	<div><yo-icon name="adjust" /><span>adjust</span></div>
	<div><yo-icon name="american-sign-language-interpreting" /><span>american-sign-language-interpreting</span></div>
	<div><yo-icon name="anchor" /><span>anchor</span></div>
	<div><yo-icon name="archive" /><span>archive</span></div>
	<div><yo-icon name="area-chart" /><span>area-chart</span></div>
	<div><yo-icon name="arrows" /><span>arrows</span></div>
	<div><yo-icon name="arrows-h" /><span>arrows-h</span></div>
	<div><yo-icon name="arrows-v" /><span>arrows-v</span></div>
	<div><yo-icon name="asl-interpreting" /><span>asl-interpreting (alias)</span></div>
	<div><yo-icon name="assistive-listening-systems" /><span>assistive-listening-systems</span></div>
	<div><yo-icon name="asterisk" /><span>asterisk</span></div>
	<div><yo-icon name="at" /><span>at</span></div>
	<div><yo-icon name="audio-description" /><span>audio-description</span></div>
	<div><yo-icon name="automobile" /><span>automobile (alias)</span></div>
	<div><yo-icon name="balance-scale" /><span>balance-scale</span></div>
	<div><yo-icon name="ban" /><span>ban</span></div>
	<div><yo-icon name="bank" /><span>bank (alias)</span></div>
	<div><yo-icon name="bar-chart" /><span>bar-chart</span></div>
	<div><yo-icon name="bar-chart-o" /><span>bar-chart-o (alias)</span></div>
	<div><yo-icon name="barcode" /><span>barcode</span></div>
	<div><yo-icon name="bars" /><span>bars</span></div>
	<div><yo-icon name="bath" /><span>bath</span></div>
	<div><yo-icon name="bathtub" /><span>bathtub (alias)</span></div>
	<div><yo-icon name="battery" /><span>battery (alias)</span></div>
	<div><yo-icon name="battery-0" /><span>battery-0 (alias)</span></div>
	<div><yo-icon name="battery-1" /><span>battery-1 (alias)</span></div>
	<div><yo-icon name="battery-2" /><span>battery-2 (alias)</span></div>
	<div><yo-icon name="battery-3" /><span>battery-3 (alias)</span></div>
	<div><yo-icon name="battery-4" /><span>battery-4 (alias)</span></div>
	<div><yo-icon name="battery-empty" /><span>battery-empty</span></div>
	<div><yo-icon name="battery-full" /><span>battery-full</span></div>
	<div><yo-icon name="battery-half" /><span>battery-half</span></div>
	<div><yo-icon name="battery-quarter" /><span>battery-quarter</span></div>
	<div><yo-icon name="battery-three-quarters" /><span>battery-three-quarters</span></div>
	<div><yo-icon name="bed" /><span>bed</span></div>
	<div><yo-icon name="beer" /><span>beer</span></div>
	<div><yo-icon name="bell" /><span>bell</span></div>
	<div><yo-icon name="bell-o" /><span>bell-o</span></div>
	<div><yo-icon name="bell-slash" /><span>bell-slash</span></div>
	<div><yo-icon name="bell-slash-o" /><span>bell-slash-o</span></div>
	<div><yo-icon name="bicycle" /><span>bicycle</span></div>
	<div><yo-icon name="binoculars" /><span>binoculars</span></div>
	<div><yo-icon name="birthday-cake" /><span>birthday-cake</span></div>
	<div><yo-icon name="blind" /><span>blind</span></div>
	<div><yo-icon name="bluetooth" /><span>bluetooth</span></div>
	<div><yo-icon name="bluetooth-b" /><span>bluetooth-b</span></div>
	<div><yo-icon name="bolt" /><span>bolt</span></div>
	<div><yo-icon name="bomb" /><span>bomb</span></div>
	<div><yo-icon name="book" /><span>book</span></div>
	<div><yo-icon name="bookmark" /><span>bookmark</span></div>
	<div><yo-icon name="bookmark-o" /><span>bookmark-o</span></div>
	<div><yo-icon name="braille" /><span>braille</span></div>
	<div><yo-icon name="briefcase" /><span>briefcase</span></div>
	<div><yo-icon name="bug" /><span>bug</span></div>
	<div><yo-icon name="building" /><span>building</span></div>
	<div><yo-icon name="building-o" /><span>building-o</span></div>
	<div><yo-icon name="bullhorn" /><span>bullhorn</span></div>
	<div><yo-icon name="bullseye" /><span>bullseye</span></div>
	<div><yo-icon name="bus" /><span>bus</span></div>
	<div><yo-icon name="cab" /><span>cab (alias)</span></div>
	<div><yo-icon name="calculator" /><span>calculator</span></div>
	<div><yo-icon name="calendar" /><span>calendar</span></div>
	<div><yo-icon name="calendar-check-o" /><span>calendar-check-o</span></div>
	<div><yo-icon name="calendar-minus-o" /><span>calendar-minus-o</span></div>
	<div><yo-icon name="calendar-o" /><span>calendar-o</span></div>
	<div><yo-icon name="calendar-plus-o" /><span>calendar-plus-o</span></div>
	<div><yo-icon name="calendar-times-o" /><span>calendar-times-o</span></div>
	<div><yo-icon name="camera" /><span>camera</span></div>
	<div><yo-icon name="camera-retro" /><span>camera-retro</span></div>
	<div><yo-icon name="car" /><span>car</span></div>
	<div><yo-icon name="caret-square-o-down" /><span>caret-square-o-down</span></div>
	<div><yo-icon name="caret-square-o-left" /><span>caret-square-o-left</span></div>
	<div><yo-icon name="caret-square-o-right" /><span>caret-square-o-right</span></div>
	<div><yo-icon name="caret-square-o-up" /><span>caret-square-o-up</span></div>
	<div><yo-icon name="cart-arrow-down" /><span>cart-arrow-down</span></div>
	<div><yo-icon name="cart-plus" /><span>cart-plus</span></div>
	<div><yo-icon name="cc" /><span>cc</span></div>
	<div><yo-icon name="certificate" /><span>certificate</span></div>
	<div><yo-icon name="check" /><span>check</span></div>
	<div><yo-icon name="check-circle" /><span>check-circle</span></div>
	<div><yo-icon name="check-circle-o" /><span>check-circle-o</span></div>
	<div><yo-icon name="check-square" /><span>check-square</span></div>
	<div><yo-icon name="check-square-o" /><span>check-square-o</span></div>
	<div><yo-icon name="child" /><span>child</span></div>
	<div><yo-icon name="circle" /><span>circle</span></div>
	<div><yo-icon name="circle-o" /><span>circle-o</span></div>
	<div><yo-icon name="circle-o-notch" /><span>circle-o-notch</span></div>
	<div><yo-icon name="circle-thin" /><span>circle-thin</span></div>
	<div><yo-icon name="clock-o" /><span>clock-o</span></div>
	<div><yo-icon name="clone" /><span>clone</span></div>
	<div><yo-icon name="close" /><span>close (alias)</span></div>
	<div><yo-icon name="cloud" /><span>cloud</span></div>
	<div><yo-icon name="cloud-download" /><span>cloud-download</span></div>
	<div><yo-icon name="cloud-upload" /><span>cloud-upload</span></div>
	<div><yo-icon name="code" /><span>code</span></div>
	<div><yo-icon name="code-fork" /><span>code-fork</span></div>
	<div><yo-icon name="coffee" /><span>coffee</span></div>
	<div><yo-icon name="cog" /><span>cog</span></div>
	<div><yo-icon name="cogs" /><span>cogs</span></div>
	<div><yo-icon name="comment" /><span>comment</span></div>
	<div><yo-icon name="comment-o" /><span>comment-o</span></div>
	<div><yo-icon name="commenting" /><span>commenting</span></div>
	<div><yo-icon name="commenting-o" /><span>commenting-o</span></div>
	<div><yo-icon name="comments" /><span>comments</span></div>
	<div><yo-icon name="comments-o" /><span>comments-o</span></div>
	<div><yo-icon name="compass" /><span>compass</span></div>
	<div><yo-icon name="copyright" /><span>copyright</span></div>
	<div><yo-icon name="creative-commons" /><span>creative-commons</span></div>
	<div><yo-icon name="credit-card" /><span>credit-card</span></div>
	<div><yo-icon name="credit-card-alt" /><span>credit-card-alt</span></div>
	<div><yo-icon name="crop" /><span>crop</span></div>
	<div><yo-icon name="crosshairs" /><span>crosshairs</span></div>
	<div><yo-icon name="cube" /><span>cube</span></div>
	<div><yo-icon name="cubes" /><span>cubes</span></div>
	<div><yo-icon name="cutlery" /><span>cutlery</span></div>
	<div><yo-icon name="dashboard" /><span>dashboard (alias)</span></div>
	<div><yo-icon name="database" /><span>database</span></div>
	<div><yo-icon name="deaf" /><span>deaf</span></div>
	<div><yo-icon name="deafness" /><span>deafness (alias)</span></div>
	<div><yo-icon name="desktop" /><span>desktop</span></div>
	<div><yo-icon name="diamond" /><span>diamond</span></div>
	<div><yo-icon name="dot-circle-o" /><span>dot-circle-o</span></div>
	<div><yo-icon name="download" /><span>download</span></div>
	<div><yo-icon name="drivers-license" /><span>drivers-license (alias)</span></div>
	<div><yo-icon name="drivers-license-o" /><span>drivers-license-o (alias)</span></div>
	<div><yo-icon name="edit" /><span>edit (alias)</span></div>
	<div><yo-icon name="ellipsis-h" /><span>ellipsis-h</span></div>
	<div><yo-icon name="ellipsis-v" /><span>ellipsis-v</span></div>
	<div><yo-icon name="envelope" /><span>envelope</span></div>
	<div><yo-icon name="envelope-o" /><span>envelope-o</span></div>
	<div><yo-icon name="envelope-open" /><span>envelope-open</span></div>
	<div><yo-icon name="envelope-open-o" /><span>envelope-open-o</span></div>
	<div><yo-icon name="envelope-square" /><span>envelope-square</span></div>
	<div><yo-icon name="eraser" /><span>eraser</span></div>
	<div><yo-icon name="exchange" /><span>exchange</span></div>
	<div><yo-icon name="exclamation" /><span>exclamation</span></div>
	<div><yo-icon name="exclamation-circle" /><span>exclamation-circle</span></div>
	<div><yo-icon name="exclamation-triangle" /><span>exclamation-triangle</span></div>
	<div><yo-icon name="external-link" /><span>external-link</span></div>
	<div><yo-icon name="external-link-square" /><span>external-link-square</span></div>
	<div><yo-icon name="eye" /><span>eye</span></div>
	<div><yo-icon name="eye-slash" /><span>eye-slash</span></div>
	<div><yo-icon name="eyedropper" /><span>eyedropper</span></div>
	<div><yo-icon name="fax" /><span>fax</span></div>
	<div><yo-icon name="feed" /><span>feed (alias)</span></div>
	<div><yo-icon name="female" /><span>female</span></div>
	<div><yo-icon name="fighter-jet" /><span>fighter-jet</span></div>
	<div><yo-icon name="file-archive-o" /><span>file-archive-o</span></div>
	<div><yo-icon name="file-audio-o" /><span>file-audio-o</span></div>
	<div><yo-icon name="file-code-o" /><span>file-code-o</span></div>
	<div><yo-icon name="file-excel-o" /><span>file-excel-o</span></div>
	<div><yo-icon name="file-image-o" /><span>file-image-o</span></div>
	<div><yo-icon name="file-movie-o" /><span>file-movie-o (alias)</span></div>
	<div><yo-icon name="file-pdf-o" /><span>file-pdf-o</span></div>
	<div><yo-icon name="file-photo-o" /><span>file-photo-o (alias)</span></div>
	<div><yo-icon name="file-picture-o" /><span>file-picture-o (alias)</span></div>
	<div><yo-icon name="file-powerpoint-o" /><span>file-powerpoint-o</span></div>
	<div><yo-icon name="file-sound-o" /><span>file-sound-o (alias)</span></div>
	<div><yo-icon name="file-video-o" /><span>file-video-o</span></div>
	<div><yo-icon name="file-word-o" /><span>file-word-o</span></div>
	<div><yo-icon name="file-zip-o" /><span>file-zip-o (alias)</span></div>
	<div><yo-icon name="film" /><span>film</span></div>
	<div><yo-icon name="filter" /><span>filter</span></div>
	<div><yo-icon name="fire" /><span>fire</span></div>
	<div><yo-icon name="fire-extinguisher" /><span>fire-extinguisher</span></div>
	<div><yo-icon name="flag" /><span>flag</span></div>
	<div><yo-icon name="flag-checkered" /><span>flag-checkered</span></div>
	<div><yo-icon name="flag-o" /><span>flag-o</span></div>
	<div><yo-icon name="flash" /><span>flash (alias)</span></div>
	<div><yo-icon name="flask" /><span>flask</span></div>
	<div><yo-icon name="folder" /><span>folder</span></div>
	<div><yo-icon name="folder-o" /><span>folder-o</span></div>
	<div><yo-icon name="folder-open" /><span>folder-open</span></div>
	<div><yo-icon name="folder-open-o" /><span>folder-open-o</span></div>
	<div><yo-icon name="frown-o" /><span>frown-o</span></div>
	<div><yo-icon name="futbol-o" /><span>futbol-o</span></div>
	<div><yo-icon name="gamepad" /><span>gamepad</span></div>
	<div><yo-icon name="gavel" /><span>gavel</span></div>
	<div><yo-icon name="gear" /><span>gear (alias)</span></div>
	<div><yo-icon name="gears" /><span>gears (alias)</span></div>
	<div><yo-icon name="gift" /><span>gift</span></div>
	<div><yo-icon name="glass" /><span>glass</span></div>
	<div><yo-icon name="globe" /><span>globe</span></div>
	<div><yo-icon name="graduation-cap" /><span>graduation-cap</span></div>
	<div><yo-icon name="group" /><span>group (alias)</span></div>
	<div><yo-icon name="hand-grab-o" /><span>hand-grab-o (alias)</span></div>
	<div><yo-icon name="hand-lizard-o" /><span>hand-lizard-o</span></div>
	<div><yo-icon name="hand-paper-o" /><span>hand-paper-o</span></div>
	<div><yo-icon name="hand-peace-o" /><span>hand-peace-o</span></div>
	<div><yo-icon name="hand-pointer-o" /><span>hand-pointer-o</span></div>
	<div><yo-icon name="hand-rock-o" /><span>hand-rock-o</span></div>
	<div><yo-icon name="hand-scissors-o" /><span>hand-scissors-o</span></div>
	<div><yo-icon name="hand-spock-o" /><span>hand-spock-o</span></div>
	<div><yo-icon name="hand-stop-o" /><span>hand-stop-o (alias)</span></div>
	<div><yo-icon name="handshake-o" /><span>handshake-o</span></div>
	<div><yo-icon name="hard-of-hearing" /><span>hard-of-hearing (alias)</span></div>
	<div><yo-icon name="hashtag" /><span>hashtag</span></div>
	<div><yo-icon name="hdd-o" /><span>hdd-o</span></div>
	<div><yo-icon name="headphones" /><span>headphones</span></div>
	<div><yo-icon name="heart" /><span>heart</span></div>
	<div><yo-icon name="heart-o" /><span>heart-o</span></div>
	<div><yo-icon name="heartbeat" /><span>heartbeat</span></div>
	<div><yo-icon name="history" /><span>history</span></div>
	<div><yo-icon name="home" /><span>home</span></div>
	<div><yo-icon name="hotel" /><span>hotel (alias)</span></div>
	<div><yo-icon name="hourglass" /><span>hourglass</span></div>
	<div><yo-icon name="hourglass-1" /><span>hourglass-1 (alias)</span></div>
	<div><yo-icon name="hourglass-2" /><span>hourglass-2 (alias)</span></div>
	<div><yo-icon name="hourglass-3" /><span>hourglass-3 (alias)</span></div>
	<div><yo-icon name="hourglass-end" /><span>hourglass-end</span></div>
	<div><yo-icon name="hourglass-half" /><span>hourglass-half</span></div>
	<div><yo-icon name="hourglass-o" /><span>hourglass-o</span></div>
	<div><yo-icon name="hourglass-start" /><span>hourglass-start</span></div>
	<div><yo-icon name="i-cursor" /><span>i-cursor</span></div>
	<div><yo-icon name="id-badge" /><span>id-badge</span></div>
	<div><yo-icon name="id-card" /><span>id-card</span></div>
	<div><yo-icon name="id-card-o" /><span>id-card-o</span></div>
	<div><yo-icon name="image" /><span>image (alias)</span></div>
	<div><yo-icon name="inbox" /><span>inbox</span></div>
	<div><yo-icon name="industry" /><span>industry</span></div>
	<div><yo-icon name="info" /><span>info</span></div>
	<div><yo-icon name="info-circle" /><span>info-circle</span></div>
	<div><yo-icon name="institution" /><span>institution (alias)</span></div>
	<div><yo-icon name="key" /><span>key</span></div>
	<div><yo-icon name="keyboard-o" /><span>keyboard-o</span></div>
	<div><yo-icon name="language" /><span>language</span></div>
	<div><yo-icon name="laptop" /><span>laptop</span></div>
	<div><yo-icon name="leaf" /><span>leaf</span></div>
	<div><yo-icon name="legal" /><span>legal (alias)</span></div>
	<div><yo-icon name="lemon-o" /><span>lemon-o</span></div>
	<div><yo-icon name="level-down" /><span>level-down</span></div>
	<div><yo-icon name="level-up" /><span>level-up</span></div>
	<div><yo-icon name="life-bouy" /><span>life-bouy (alias)</span></div>
	<div><yo-icon name="life-buoy" /><span>life-buoy (alias)</span></div>
	<div><yo-icon name="life-ring" /><span>life-ring</span></div>
	<div><yo-icon name="life-saver" /><span>life-saver (alias)</span></div>
	<div><yo-icon name="lightbulb-o" /><span>lightbulb-o</span></div>
	<div><yo-icon name="line-chart" /><span>line-chart</span></div>
	<div><yo-icon name="location-arrow" /><span>location-arrow</span></div>
	<div><yo-icon name="lock" /><span>lock</span></div>
	<div><yo-icon name="low-vision" /><span>low-vision</span></div>
	<div><yo-icon name="magic" /><span>magic</span></div>
	<div><yo-icon name="magnet" /><span>magnet</span></div>
	<div><yo-icon name="mail-forward" /><span>mail-forward (alias)</span></div>
	<div><yo-icon name="mail-reply" /><span>mail-reply (alias)</span></div>
	<div><yo-icon name="mail-reply-all" /><span>mail-reply-all (alias)</span></div>
	<div><yo-icon name="male" /><span>male</span></div>
	<div><yo-icon name="map" /><span>map</span></div>
	<div><yo-icon name="map-marker" /><span>map-marker</span></div>
	<div><yo-icon name="map-o" /><span>map-o</span></div>
	<div><yo-icon name="map-pin" /><span>map-pin</span></div>
	<div><yo-icon name="map-signs" /><span>map-signs</span></div>
	<div><yo-icon name="meh-o" /><span>meh-o</span></div>
	<div><yo-icon name="microchip" /><span>microchip</span></div>
	<div><yo-icon name="microphone" /><span>microphone</span></div>
	<div><yo-icon name="microphone-slash" /><span>microphone-slash</span></div>
	<div><yo-icon name="minus" /><span>minus</span></div>
	<div><yo-icon name="minus-circle" /><span>minus-circle</span></div>
	<div><yo-icon name="minus-square" /><span>minus-square</span></div>
	<div><yo-icon name="minus-square-o" /><span>minus-square-o</span></div>
	<div><yo-icon name="mobile" /><span>mobile</span></div>
	<div><yo-icon name="mobile-phone" /><span>mobile-phone (alias)</span></div>
	<div><yo-icon name="money" /><span>money</span></div>
	<div><yo-icon name="moon-o" /><span>moon-o</span></div>
	<div><yo-icon name="mortar-board" /><span>mortar-board (alias)</span></div>
	<div><yo-icon name="motorcycle" /><span>motorcycle</span></div>
	<div><yo-icon name="mouse-pointer" /><span>mouse-pointer</span></div>
	<div><yo-icon name="music" /><span>music</span></div>
	<div><yo-icon name="navicon" /><span>navicon (alias)</span></div>
	<div><yo-icon name="newspaper-o" /><span>newspaper-o</span></div>
	<div><yo-icon name="object-group" /><span>object-group</span></div>
	<div><yo-icon name="object-ungroup" /><span>object-ungroup</span></div>
	<div><yo-icon name="paint-brush" /><span>paint-brush</span></div>
	<div><yo-icon name="paper-plane" /><span>paper-plane</span></div>
	<div><yo-icon name="paper-plane-o" /><span>paper-plane-o</span></div>
	<div><yo-icon name="paw" /><span>paw</span></div>
	<div><yo-icon name="pencil" /><span>pencil</span></div>
	<div><yo-icon name="pencil-square" /><span>pencil-square</span></div>
	<div><yo-icon name="pencil-square-o" /><span>pencil-square-o</span></div>
	<div><yo-icon name="percent" /><span>percent</span></div>
	<div><yo-icon name="phone" /><span>phone</span></div>
	<div><yo-icon name="phone-square" /><span>phone-square</span></div>
	<div><yo-icon name="photo" /><span>photo (alias)</span></div>
	<div><yo-icon name="picture-o" /><span>picture-o</span></div>
	<div><yo-icon name="pie-chart" /><span>pie-chart</span></div>
	<div><yo-icon name="plane" /><span>plane</span></div>
	<div><yo-icon name="plug" /><span>plug</span></div>
	<div><yo-icon name="plus" /><span>plus</span></div>
	<div><yo-icon name="plus-circle" /><span>plus-circle</span></div>
	<div><yo-icon name="plus-square" /><span>plus-square</span></div>
	<div><yo-icon name="plus-square-o" /><span>plus-square-o</span></div>
	<div><yo-icon name="podcast" /><span>podcast</span></div>
	<div><yo-icon name="power-off" /><span>power-off</span></div>
	<div><yo-icon name="print" /><span>print</span></div>
	<div><yo-icon name="puzzle-piece" /><span>puzzle-piece</span></div>
	<div><yo-icon name="qrcode" /><span>qrcode</span></div>
	<div><yo-icon name="question" /><span>question</span></div>
	<div><yo-icon name="question-circle" /><span>question-circle</span></div>
	<div><yo-icon name="question-circle-o" /><span>question-circle-o</span></div>
	<div><yo-icon name="quote-left" /><span>quote-left</span></div>
	<div><yo-icon name="quote-right" /><span>quote-right</span></div>
	<div><yo-icon name="random" /><span>random</span></div>
	<div><yo-icon name="recycle" /><span>recycle</span></div>
	<div><yo-icon name="refresh" /><span>refresh</span></div>
	<div><yo-icon name="registered" /><span>registered</span></div>
	<div><yo-icon name="remove" /><span>remove (alias)</span></div>
	<div><yo-icon name="reorder" /><span>reorder (alias)</span></div>
	<div><yo-icon name="reply" /><span>reply</span></div>
	<div><yo-icon name="reply-all" /><span>reply-all</span></div>
	<div><yo-icon name="retweet" /><span>retweet</span></div>
	<div><yo-icon name="road" /><span>road</span></div>
	<div><yo-icon name="rocket" /><span>rocket</span></div>
	<div><yo-icon name="rss" /><span>rss</span></div>
	<div><yo-icon name="rss-square" /><span>rss-square</span></div>
	<div><yo-icon name="s15" /><span>s15 (alias)</span></div>
	<div><yo-icon name="search" /><span>search</span></div>
	<div><yo-icon name="search-minus" /><span>search-minus</span></div>
	<div><yo-icon name="search-plus" /><span>search-plus</span></div>
	<div><yo-icon name="send" /><span>send (alias)</span></div>
	<div><yo-icon name="send-o" /><span>send-o (alias)</span></div>
	<div><yo-icon name="server" /><span>server</span></div>
	<div><yo-icon name="share" /><span>share</span></div>
	<div><yo-icon name="share-alt" /><span>share-alt</span></div>
	<div><yo-icon name="share-alt-square" /><span>share-alt-square</span></div>
	<div><yo-icon name="share-square" /><span>share-square</span></div>
	<div><yo-icon name="share-square-o" /><span>share-square-o</span></div>
	<div><yo-icon name="shield" /><span>shield</span></div>
	<div><yo-icon name="ship" /><span>ship</span></div>
	<div><yo-icon name="shopping-bag" /><span>shopping-bag</span></div>
	<div><yo-icon name="shopping-basket" /><span>shopping-basket</span></div>
	<div><yo-icon name="shopping-cart" /><span>shopping-cart</span></div>
	<div><yo-icon name="shower" /><span>shower</span></div>
	<div><yo-icon name="sign-in" /><span>sign-in</span></div>
	<div><yo-icon name="sign-language" /><span>sign-language</span></div>
	<div><yo-icon name="sign-out" /><span>sign-out</span></div>
	<div><yo-icon name="signal" /><span>signal</span></div>
	<div><yo-icon name="signing" /><span>signing (alias)</span></div>
	<div><yo-icon name="sitemap" /><span>sitemap</span></div>
	<div><yo-icon name="sliders" /><span>sliders</span></div>
	<div><yo-icon name="smile-o" /><span>smile-o</span></div>
	<div><yo-icon name="snowflake-o" /><span>snowflake-o</span></div>
	<div><yo-icon name="soccer-ball-o" /><span>soccer-ball-o (alias)</span></div>
	<div><yo-icon name="sort" /><span>sort</span></div>
	<div><yo-icon name="sort-alpha-asc" /><span>sort-alpha-asc</span></div>
	<div><yo-icon name="sort-alpha-desc" /><span>sort-alpha-desc</span></div>
	<div><yo-icon name="sort-amount-asc" /><span>sort-amount-asc</span></div>
	<div><yo-icon name="sort-amount-desc" /><span>sort-amount-desc</span></div>
	<div><yo-icon name="sort-asc" /><span>sort-asc</span></div>
	<div><yo-icon name="sort-desc" /><span>sort-desc</span></div>
	<div><yo-icon name="sort-down" /><span>sort-down (alias)</span></div>
	<div><yo-icon name="sort-numeric-asc" /><span>sort-numeric-asc</span></div>
	<div><yo-icon name="sort-numeric-desc" /><span>sort-numeric-desc</span></div>
	<div><yo-icon name="sort-up" /><span>sort-up (alias)</span></div>
	<div><yo-icon name="space-shuttle" /><span>space-shuttle</span></div>
	<div><yo-icon name="spinner" /><span>spinner</span></div>
	<div><yo-icon name="spoon" /><span>spoon</span></div>
	<div><yo-icon name="square" /><span>square</span></div>
	<div><yo-icon name="square-o" /><span>square-o</span></div>
	<div><yo-icon name="star" /><span>star</span></div>
	<div><yo-icon name="star-half" /><span>star-half</span></div>
	<div><yo-icon name="star-half-empty" /><span>star-half-empty (alias)</span></div>
	<div><yo-icon name="star-half-full" /><span>star-half-full (alias)</span></div>
	<div><yo-icon name="star-half-o" /><span>star-half-o</span></div>
	<div><yo-icon name="star-o" /><span>star-o</span></div>
	<div><yo-icon name="sticky-note" /><span>sticky-note</span></div>
	<div><yo-icon name="sticky-note-o" /><span>sticky-note-o</span></div>
	<div><yo-icon name="street-view" /><span>street-view</span></div>
	<div><yo-icon name="suitcase" /><span>suitcase</span></div>
	<div><yo-icon name="sun-o" /><span>sun-o</span></div>
	<div><yo-icon name="support" /><span>support (alias)</span></div>
	<div><yo-icon name="tablet" /><span>tablet</span></div>
	<div><yo-icon name="tachometer" /><span>tachometer</span></div>
	<div><yo-icon name="tag" /><span>tag</span></div>
	<div><yo-icon name="tags" /><span>tags</span></div>
	<div><yo-icon name="tasks" /><span>tasks</span></div>
	<div><yo-icon name="taxi" /><span>taxi</span></div>
	<div><yo-icon name="television" /><span>television</span></div>
	<div><yo-icon name="terminal" /><span>terminal</span></div>
	<div><yo-icon name="thermometer" /><span>thermometer (alias)</span></div>
	<div><yo-icon name="thermometer-0" /><span>thermometer-0 (alias)</span></div>
	<div><yo-icon name="thermometer-1" /><span>thermometer-1 (alias)</span></div>
	<div><yo-icon name="thermometer-2" /><span>thermometer-2 (alias)</span></div>
	<div><yo-icon name="thermometer-3" /><span>thermometer-3 (alias)</span></div>
	<div><yo-icon name="thermometer-4" /><span>thermometer-4 (alias)</span></div>
	<div><yo-icon name="thermometer-empty" /><span>thermometer-empty</span></div>
	<div><yo-icon name="thermometer-full" /><span>thermometer-full</span></div>
	<div><yo-icon name="thermometer-half" /><span>thermometer-half</span></div>
	<div><yo-icon name="thermometer-quarter" /><span>thermometer-quarter</span></div>
	<div><yo-icon name="thermometer-three-quarters" /><span>thermometer-three-quarters</span></div>
	<div><yo-icon name="thumb-tack" /><span>thumb-tack</span></div>
	<div><yo-icon name="thumbs-down" /><span>thumbs-down</span></div>
	<div><yo-icon name="thumbs-o-down" /><span>thumbs-o-down</span></div>
	<div><yo-icon name="thumbs-o-up" /><span>thumbs-o-up</span></div>
	<div><yo-icon name="thumbs-up" /><span>thumbs-up</span></div>
	<div><yo-icon name="ticket" /><span>ticket</span></div>
	<div><yo-icon name="times" /><span>times</span></div>
	<div><yo-icon name="times-circle" /><span>times-circle</span></div>
	<div><yo-icon name="times-circle-o" /><span>times-circle-o</span></div>
	<div><yo-icon name="times-rectangle" /><span>times-rectangle (alias)</span></div>
	<div><yo-icon name="times-rectangle-o" /><span>times-rectangle-o (alias)</span></div>
	<div><yo-icon name="tint" /><span>tint</span></div>
	<div><yo-icon name="toggle-down" /><span>toggle-down (alias)</span></div>
	<div><yo-icon name="toggle-left" /><span>toggle-left (alias)</span></div>
	<div><yo-icon name="toggle-off" /><span>toggle-off</span></div>
	<div><yo-icon name="toggle-on" /><span>toggle-on</span></div>
	<div><yo-icon name="toggle-right" /><span>toggle-right (alias)</span></div>
	<div><yo-icon name="toggle-up" /><span>toggle-up (alias)</span></div>
	<div><yo-icon name="trademark" /><span>trademark</span></div>
	<div><yo-icon name="trash" /><span>trash</span></div>
	<div><yo-icon name="trash-o" /><span>trash-o</span></div>
	<div><yo-icon name="tree" /><span>tree</span></div>
	<div><yo-icon name="trophy" /><span>trophy</span></div>
	<div><yo-icon name="truck" /><span>truck</span></div>
	<div><yo-icon name="tty" /><span>tty</span></div>
	<div><yo-icon name="tv" /><span>tv (alias)</span></div>
	<div><yo-icon name="umbrella" /><span>umbrella</span></div>
	<div><yo-icon name="universal-access" /><span>universal-access</span></div>
	<div><yo-icon name="university" /><span>university</span></div>
	<div><yo-icon name="unlock" /><span>unlock</span></div>
	<div><yo-icon name="unlock-alt" /><span>unlock-alt</span></div>
	<div><yo-icon name="unsorted" /><span>unsorted (alias)</span></div>
	<div><yo-icon name="upload" /><span>upload</span></div>
	<div><yo-icon name="user" /><span>user</span></div>
	<div><yo-icon name="user-circle" /><span>user-circle</span></div>
	<div><yo-icon name="user-circle-o" /><span>user-circle-o</span></div>
	<div><yo-icon name="user-o" /><span>user-o</span></div>
	<div><yo-icon name="user-plus" /><span>user-plus</span></div>
	<div><yo-icon name="user-secret" /><span>user-secret</span></div>
	<div><yo-icon name="user-times" /><span>user-times</span></div>
	<div><yo-icon name="users" /><span>users</span></div>
	<div><yo-icon name="vcard" /><span>vcard (alias)</span></div>
	<div><yo-icon name="vcard-o" /><span>vcard-o (alias)</span></div>
	<div><yo-icon name="video-camera" /><span>video-camera</span></div>
	<div><yo-icon name="volume-control-phone" /><span>volume-control-phone</span></div>
	<div><yo-icon name="volume-down" /><span>volume-down</span></div>
	<div><yo-icon name="volume-off" /><span>volume-off</span></div>
	<div><yo-icon name="volume-up" /><span>volume-up</span></div>
	<div><yo-icon name="warning" /><span>warning (alias)</span></div>
	<div><yo-icon name="wheelchair" /><span>wheelchair</span></div>
	<div><yo-icon name="wheelchair-alt" /><span>wheelchair-alt</span></div>
	<div><yo-icon name="wifi" /><span>wifi</span></div>
	<div><yo-icon name="window-close" /><span>window-close</span></div>
	<div><yo-icon name="window-close-o" /><span>window-close-o</span></div>
	<div><yo-icon name="window-maximize" /><span>window-maximize</span></div>
	<div><yo-icon name="window-minimize" /><span>window-minimize</span></div>
	<div><yo-icon name="window-restore" /><span>window-restore</span></div>
	<div><yo-icon name="wrench" /><span>wrench</span></div>
</div>
</template>

<script>
import YoIcon from '../components/yo-icon'

export default {
	components: { YoIcon }
}
</script>

<style lang="sass">
.demo-icon
	div
		position: relative
		width: 100%
		height: 40px
		font-size: 24px

		.yo-icon
			position: absolute
			width: 40px
			line-height: 40px
			text-align: center

		span
			display: inline-block
			line-height: 40px
			margin-left: 50px
			font-size: 12px
</style>
